POST http://localhost:3000/api/cart
Content-Type: application/json
#Cookie: cartToken=11111
#{
#  "fullName": "Roma Andreyuk",
#  "email": "Roma@example.com",
#  "password": "5510515318"
#
#}
#

#{
 # "quantity": 5
#}
{
  "productItemId": 3,
  "ingredients": [1,2,3,4,5,6,7,8,9]
}