import { Metadata } from 'next';
import { Header } from '@/shared/components/shared/header';
import { Container } from '@/shared/components/shared/container';
import React, { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense fallback={null}>
          <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
